### ISSUE TITLE
Text boxes need to be un-focuseable

### ISSUE THREAD

**Issue by Some-Birb7190** [lilopkins/evidenceangel#73]
Upon deleting a piece of evidence, the view re-centers itself back on the last selected text box which can confused the user as it is moving content for no discernable reason

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the DeleteEvidenceAt input handler to maintain the scroll position when deleting evidence. This prevents the view from re-centering and confusing the user.

You can review changes in this commit: https://github.com/mnmnk43434/lilopkins-evidenceangel-73/commit/19cb778d6744dce47bab1e3ab503389fef3f261e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
