### ISSUE TITLE
Author in metadata is not escaped and displayed properly

### ISSUE THREAD

**Issue by Some-Birb7190** [lilopkins/evidenceangel#75]
if a `<` or a `>` character is in the author or email box, it doesn't display anything in evidenceangel. Exporting them is fine and is properly escaped on html export
[Screencast From 2024-12-07 15-23-01.webm](https://github.com/user-attachments/assets/b1751e49-44b2-4a0f-903d-778508d94a08)

**Comment by lilopkins** [comment]
Additionally, if you could post the log lines with the `SetAuthor` (or whatever it's called) events in that would be a good help to understand what is actually being processed.

**Comment by Some-Birb7190** [comment]
Re your first reply, yes it is, using the first example on that site yields:
![image](https://github.com/user-attachments/assets/e1a11946-4139-4bea-b6b0-15b81cab8baf)

Your second reply:
```
(evidenceangel-ui:11361): Gtk-WARNING **: 15:31:09.655: Failed to set text '<an author' from markup due to error parsing markup: Error on line 1 char 20: “author<” is not a valid name: “<”

(evidenceangel-ui:11361): Gtk-WARNING **: 15:31:09.655: Failed to set text '<an email' from markup due to error parsing markup: Error on line 1 char 19: “email<” is not a valid name: “<”

(evidenceangel-ui:11361): Gtk-WARNING **: 15:31:09.655: Failed to set text '<h1>closing the tags</h1>' from markup due to error parsing markup: Unknown tag 'h1' on line 1 char 21

(evidenceangel-ui:11361): Gtk-WARNING **: 15:31:09.655: Failed to set text '<h1>doesnt work</h1>' from markup due to error parsing markup: Unknown tag 'h1' on line 1 char 21
context mismatch in svga_surface_destroy
[2024-12-07 15:31:37.548383867 +00:00 DEBUG evidenceangel_ui::app] Handling event: CreateAuthor
[2024-12-07 15:31:39.818743786 +00:00 DEBUG evidenceangel_ui::app] Handling event: _CreateAuthor(Author { name: "<span foreground=\"blue\" size=\"x-large\">Blue text</span> is <i>cool</i>!", email: None })
```
Yeah it's clear what it's rendering there

**Comment by lilopkins** [comment]
I suppose to some extent this is a GIGO situation... should be a simple change to https://github.com/lilopkins/evidenceangel/blob/7c44854ca201144e46b99d1d3e73f9f3f33b9454/src/evidenceangel-ui/author_factory.rs#L36-L37 to resolve anyway.

**Comment by Some-Birb7190** [comment]
I personally think it would be beneficial to strip that and make it purely plain text, the need for pango rendering inside a box like that isn't necessary when none of the other boxes support it.

**Comment by lilopkins** [comment]
Yes indeed. Looks like all it needs is one line to tell it not to use markup during rendering. From the adwaita docs:
![bild](https://github.com/user-attachments/assets/c88bdfe4-3f6b-4679-8e18-8e0eaaf2fdd4)

**Comment by Some-Birb7190** [comment]
Being stupid, where and how does that get implemented, I'll make the change and but not sure where that preference lives

**Comment by lilopkins** [comment]
At a guess it'll be a new line below where I specified earlier:
```rs
set_use_markup: false,
```

**Comment by Some-Birb7190** [comment]
I will wait until you are available so I can do it in a proper environment in an IDE
