### ISSUE TITLE
Attaching different files but with the same file name

### ISSUE THREAD

**Issue by Some-Birb7190** [lilopkins/evidenceangel#98]
As a user, I want to add files that have the same name, for example applications naming things 'screenshot.jpeg', So that I can use the caption to better explain what the image should be.

**Comment by lilopkins** [comment]
What is the current behavour of this in the latest rc?

**Comment by Some-Birb7190** [comment]
![image](https://github.com/user-attachments/assets/a9977ec6-7397-4a47-8659-5b078f44d065)

**Comment by lilopkins** [comment]
I'm a little hesitant to change file names on export -- I could disambiguate by test case name as a folder if you think that will help?

Can you provide a use case where the files would be the same name and need disambiguation by caption?

**Comment by lilopkins** [comment]
I think I've found a compromise. It now stores in a folder named for the test case (i.e. implicit disambiguation by test case), followed by only adding the caption if there are two files with the same name. If there are clashing files with no captions, the error is still returned (as there is no sensible way to disambiguate them).

**Comment by Some-Birb7190** [comment]
I was going to suggest that, I didn't get here quick enough. If you structure the zip file for full packages as `/[package name]/[test case name]/[file]` or something similar.

I don't know how you'd get around having the same named file in the same test case, unless you disambiguate it by caption, but like you said that changes the file name...
